accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'account'

urlpatterns = [
    path('register/',UserRegistrationView,name="register"),
    path('login/',UserLoginView,name="login"),
]

newsbuddy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('annotation/',include('annotation.urls')),
    path('accounts/',include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin,BaseUserManager
# Create your models here.

class UserAccountManager(BaseUserManager):
    def create_user(self,email,password,name):
        if not email:
            raise ValueError("Users must have an email address")
        if not password:
            raise ValueError("Users must have a password")
        
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            password=password,
            name = name,
            )
        user.set_password(password)
        user.save()

        return user
    
    def create_superuser(self,email,password,**other_fields):
        user = self.create_user(email,password,**other_fields)

        user.is_staff = True
        user.is_superuser = True
        user.access = 0
        user.save()

        return user


class UserAccount(AbstractBaseUser,PermissionsMixin):
    id = models.AutoField(primary_key=True)
    email = models.EmailField(max_length=50, unique=True)
    name = models.CharField(max_length=30)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    
    objects = UserAccountManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["name", ]

    def get_full_name(self):
        return self.name 

    def get_short_name(self):
        return self.name 

    def __str__(self):
        return self.email

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm,AuthenticationForm
from .models import UserAccount
from django.contrib.auth import authenticate

class UserAccountCreationForm(UserCreationForm):
    class Meta:
        model = UserAccount
        fields = ('email',"name","password1","password2",)

class UserLoginForm(forms.ModelForm):
    email = forms.CharField(label ="Email",widget=forms.TextInput(attrs={
        'class':'form-control',
        'id':"name",
        'placeholder':'Email Address'
    }))
    password = forms.CharField(label="Password",widget=forms.PasswordInput(attrs={
        'class':'form-control',
        'placeholder':'Password'
    }))
    class Meta:
        model = UserAccount
        fields = ("email","password")

    def clean(self):
        email = self.cleaned_data["email"]
        password = self.cleaned_data["password"]

        if not authenticate(email = email,password = password):
            raise forms.ValidationError("Invalid Credentials")

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,authenticate,logout
from accounts.forms import UserAccountCreationForm,UserLoginForm
from django.http import HttpResponse
from django.contrib.auth.views import logout_then_login
# Create your views here.

def UserRegistrationView(request):
    context = {}
    if request.POST:
        form =  UserAccountCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            return redirect('/annotation/home',request)
        else:
            context['registration_form'] = form
    else:
        form = UserAccountCreationForm()
        context['registration_form'] = form
    return render(request, 'accounts/register.html',context)

def UserLoginView(request):
    context = {}
    user = request.user
    if user.is_authenticated:
        return logout_then_login(request,'login')
    if request.POST:
        form =  UserLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password')
            account = authenticate(email=email, password=raw_password)
            if account:
                login(request, account)
                return redirect("/annotation/home",request)
        else:
            context['login_form'] = form
    else:
        form = UserLoginForm()
        context['login_form'] = form
    return render(request,'accounts/login.html',context)

accounts/templates/accounts/login.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
    <head>
        <title>Login Page</title>
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/signin.css' %}"/>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    </head>
    <body>
        <div class="form">
            <form class="form-horizontal signin" method="post">
                {% csrf_token %}
                <div class="form-wrap" style="position: relative;">                
                    <h2>Login</h2>
                    <div class="form-group">
                      <div class="relative">
                          {{login_form.email}}
                          <!-- <input class="form-control" id="name" type="text" required="" autofocus="" title="" autocomplete="" placeholder="Email Address"> -->
                          <i class="fa fa-envelope"></i>
                      </div>
                    </div>
                    <div class="form-group">
                        <div class="relative">
                            {{login_form.password}}
                            <!-- <input class="form-control" type="password" required="" placeholder="Password"> -->
                            <i class="fa fa-key"></i>
                        </div>
                        <span class="pull-right"><small><a href="#">Forgot Password?</a></small></span>
                    </div> 
                    <div class="login-btn">
                        <a href="#"><button class="movebtn movebtnsu" type="Submit">Login <i class="fa fa-fw fa-lock"></i></button></a>
                        <!-- <div class="relative"><hr><span class="login-text">or login with</span></div>
                        <div class="clearfix"></div>
                        <div class="social-btn clearfix">
                            <a href="#"><button class="movebtn google" type="Submit">Google <i class="fa fa-fw fa-google"></i></button></a>
                            <a href="#"><button class="movebtn facebook" type="Submit">Facebook <i class="fa fa-fw fa-facebook"></i></button></a>
                        </div> -->
                    </div>
                </div>
                <div class="sign-up">
                    <a href="{% url 'account:register'%}" class="signbtn"><small>Not a member? Sign Up <i>(Click me)</i></small></a>
                </div>
            </form>
        </div>
        <!-- <script src="{% static 'js/signin.js' %}"></script> -->
    </body>
</html>    

<!-- <h2>Log In</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Log In</button>
</form> -->

accounts/templates/accounts/register.html
<!-- <h2>Register</h2>
<form method="post">
    {% csrf_token %}
    {% for field in registration_form %}
        <p>
            {{field.label_tag}}
            {{field}}

            {% for error in field.errors %}
                <p style="color:red;">{{error}}</p>
            {% endfor %}
        </p>
    {% endfor %}

    <button type="submit">Register</button>
</form> -->

{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
    <head>
        <title>Login Page</title>
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/signin.css' %}"/>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    </head>
    <body>
        <div class="form">
            <form class="form-horizontal signup" method="post">
                {% csrf_token %}
                <div class="form-wrap" style="position: relative;">
                    <h2>Register</h2>
                    <div class="form-group">
                        <div class="relative">
                            {{registration_form.email|add_class:"form-control"|attr:"placeholder:Email Address"}}
                            <!-- <input class="form-control" id="name" type="text" required="" autofocus="" title="" autocomplete="" placeholder="Email Address"> -->
                            <i class="fa fa-envelope"></i>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="relative">
                            {{registration_form.name|add_class:"form-control"|attr:"placeholder:Name"}}
                            <!-- <input class="form-control" id="name" type="text" required="" autofocus="" title="" autocomplete="" placeholder="Your name"> -->
                            <i class="fa fa-user"></i>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="relative">
                            {{registration_form.password1|add_class:"form-control"|attr:"placeholder:Password"}}
                            <!-- <input id="myinput" class="form-control" type="password" required="" placeholder="Password"> -->
                            <i class="fa fa-key"></i>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="relative">
                            {{registration_form.password2|add_class:"form-control"|attr:"placeholder:Confirm Password"}}
                            <!-- <input id="myinput" class="form-control" type="password" required="" placeholder="Password"> -->
                            <i class="fa fa-key"></i>
                        </div>
                    </div>    
                    <!-- <span class="pull-right"><small><a href="#" id="showhide">show / hide</a></small></span> -->
                           
                    <div class="login-btn">
                        <a href="#"><button class="movebtn movebtnsu" type="Submit">Submit <i class="fa fa-fw fa-paper-plane"></i></button></a>
                        <!-- <div class="relative"><hr><span class="login-text">or signup with</span></div>
                        <div class="clearfix"></div>
                        <div class="social-btn clearfix">
                            <a href="#"><button class="movebtn google" type="Submit">Google <i class="fa fa-fw fa-google"></i></button></a>
                            <a href="#"><button class="movebtn facebook" type="Submit">Facebook <i class="fa fa-fw fa-facebook"></i></button></a>
                        </div> -->
                    </div>
                </div>
                <div class="sign-up">
                  <a href="{% url 'account:login' %}" class="signbtn"><small>Already member? Sign in <i>(Click me)</i></small></a>
                </div>
            </form>
        </div>
        <!-- <script src="{% static 'js/signin.js' %}"></script> -->
    </body>
</html>    

<!-- <h2>Log In</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Log In</button>
</form> -->