accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'account'

urlpatterns = [
    path('register/',UserRegistrationView,name="register"),
    path('login/',UserLoginView,name="login"),
]

annotation/urls.py
from django.urls import path,include
from rest_framework.routers import DefaultRouter
# from .views import ArticleViewSet,AnnotationViewSet,CommentViewSet
from . import views

app_name = 'annotation'
urlpatterns = [
    # path ("",include(router.urls)),
    path("article_view",views.get_article,name = 'article_view'),
    path("home",views.home,name = 'home'),
    path('add_annotation',views.add_annotation,name = 'add_annotation'),
    path('vote', views.vote, name='vote'),
    path('profile',views.profile, name = 'profile')
]

newsbuddy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('annotation/',include('annotation.urls')),
    path('accounts/',include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

annotation/models.py
from django.db import models
from accounts.models import UserAccount
# Create your models here.
class Article(models.Model):
    link = models.URLField(max_length=255)
    title = models.CharField(max_length =200)
    author = models.CharField(max_length = 200)
    def __str__(self):
        return str(self.link)

# class Annotation(models.Model):
#     article = models.ForeignKey(Line,on_delete=models.CASCADE,related_name='annotations')
#     start_index = models.IntegerField()
#     end_index = models.IntegerField()
#     created_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return str(self.created_at)
class Line(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE)
    total_upvotes  = models.IntegerField(default = 0)
    total_downvotes = models.IntegerField(default = 0)
    total_agree= models.IntegerField(default = 0)
    total_disagree = models.IntegerField(default = 0)
    text  = models.CharField(max_length =100)
    def __str__(self):
        return str(self.text)

class Comment(models.Model):
    user = models.ForeignKey(UserAccount,on_delete = models.CASCADE)
    line = models.ForeignKey(Line,on_delete=models.CASCADE,related_name='comments')
    upvotes = models.IntegerField(default = 0)
    downvotes = models.IntegerField(default = 0)
    references = models.CharField(max_length=1024)
    created_at = models.DateTimeField(auto_now_add=True)
    opinion = models.CharField(max_length = 1024)
    name = models.CharField(max_length  = 100,default = "John")
    agree = models.BooleanField(default = False)
    
    def __str__(self):
        return str(self.references) + " " +str(self.created_at) 

# class User(models.Model):
#     name = models.CharField(max_length = 100)
#     email = models.CharField(max_length = 100)
#     password = models.CharField(max_length =100)
#     def __str__(self):
#         return str({self.name} + " " +{self.email})

# # article
# # for lines in article.get_lines
# #     # pie chart line.total_upvotes and total_downvotes
# #     for comment in line.get_comments# to show top 5 comments 

# # server->object->template-rendering->

annotation/views.py
from django.shortcuts import render
from rest_framework.viewsets import ModelViewSet
from .models import *
from accounts.models import UserAccount
# from .serializers import ArticleSerializer,AnnotationSerializer,CommentSerializer
from django.http import HttpResponse
import trafilatura
from django.http import JsonResponse
# Create your views here.
# class ArticleViewSet(ModelViewSet):
#     serializer_class = ArticleSerializer
#     queryset = Article.objects.all()

# class AnnotationViewSet(ModelViewSet):
#     serializer_class = AnnotationSerializer
#     queryset = Annotation.objects.all()

# class CommentViewSet(ModelViewSet):
#     serializer_class = CommentSerializer
#     queryset = Comment.objects.all()

def home(request):
    return render(request,'homepage.html')

def profile(request):
    return render(request,'userprofile.html',context  = {'user':request.user})

def add_annotation(request):
    print(request.POST)
    line_id = request.POST['id']
    text = request.POST['text']
    link1 = request.POST['link']
    # link2 = request.POST['link2']
    agree  = request.POST['agree']
    agree = str.lower(agree)
    print(agree)
    line = Line.objects.get(id = line_id)
    if agree == 'yes':
        line.total_upvotes += 1
    else:
        line.total_downvotes += 1
    comment = Comment(user = request.user ,line =  line, references = str(link1) ,opinion = text,agree = agree == "yes")
    comment.save()
    line.save()
    return render(request,'index.html',context = {'article':line.article})

def vote(request):
    comment_id = request.POST['id']
    vote_amt = int(request.POST['vote'])
    comment = Comment.objects.get(id= comment_id)
    line = comment.line
    if vote_amt > 0:
        comment.upvotes +=1
        line.total_upvotes+=1
    else:
        comment.downvotes -=1
        line.total_downvotes -=1
    line.save()
    comment.save()
    return JsonResponse({'done':True})

    # comment.article.total_upvotes+=1
def get_article(request):
    url = request.POST.get('url',None)
    if url is not None and url!='':
        try:
            article  = Article.objects.get(link = url)
        except Article.DoesNotExist as e:
            downloaded = trafilatura.fetch_url(url)
            text = trafilatura.bare_extraction(downloaded,include_images = True,include_links=True,include_formatting = True)
            article = Article(link = url,author = text['author'] if text['author'] is not None else "Author",title = text['title'] if text['title'] is not None else "Title")
            article.save()
            for line in text['text'].split('.'):
                Line(text = line, article = article).save()
        # return HttpResponse(f"{article}")
        return render(request,'index.html',context = {'article':article})

annotation/templates/homepage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Pathway+Gothic+One&display=swap" rel="stylesheet">
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <title>Welcome to NewsBuddy</title>
    <style>
        body{
            overflow:hidden !important;
        }
        *{
            font-family: "Pathway Gothic One" !important;
        }
        .ui.fluid.container{
            background: url({% static 'homeBackground.svg' %});
            background-repeat: no-repeat;
            background-size: cover;
            height: calc(100vh + 1rem) !important;
        }
        .mainContainer{
            margin-top: 15vh;
        }
        .heading{
            font-size: 10em !important;
            color: white !important;
        }
        .subHeading{
            font-size: 4em !important;
        }
        .searchBar{
            height: 6vh !important;
            width: 50% !important;
            letter-spacing: 3em !important;
            font-size: 1.5em !important;
        }
        input{
            font-family: Montserrat !important;
        }
        .searchButton{
            width: 16% !important;
            background-color: #85a6d4;
            font-family: Montserrat !important;
            padding-left: 3.3rem !important;
            font-weight: normal !important;
            font-size: 1.1em !important;
            text-align: center !important;
        }
        .menuContainer{
            margin-top: calc(31.5vh) !important;
        }
        .item{
            font-size: 2em !important;
            color: white !important;
        }
    </style>
</head>
<body>
    <div class="ui fluid container">
        <div class="ui center aligned grid">
            <div class="ui sixteen wide column mainContainer">
                <div class="ui header heading">
                    NewsBuddy
                </div>
                <div class="ui header heading subHeading">
                    Truth for the people, Truth by the people
                </div>
                <br><br><br>
                <div class="ui action input searchBar ">
                    <form action="{% url 'annotation:article_view' %}" method="post">
                        {% csrf_token %}
                    <input type="text" placeholder="Enter news article link here &nbsp " name = "url" >
                    <button class="ui primary button searchButton">Go</button>
                </form>
                </div>
                <!-- <div class="ui fluid container"> -->
                <div class="ui center aligned grid menuContainer">
                    <div class="ui menu" style="background: transparent !important; border: none !important">                        
                        <div class="menu">
                            <div class="borderless item">
                                About NewsBuddy
                            </div>
                            <div class="borderless item">
                                How It Works
                            </div>
                            <div class="borderless item">
                                The Team
                            </div>
                            <div class="borderless item">
                                <a href="{% url 'annotation:profile' %} " style="color: white">
                                    Profile
                                </a>
                            </div>                    
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

annotation/templates/userprofile.html
<!-- Add icon library -->
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style type="text/css">
    .card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 900px;
  margin: auto;
  text-align: center;
  /*height: 100%;*/
  /*background: url({% static 'homeBackground.svg' %})*/
  background: #fbfafd
}


.title {
  color: rgb(0, 0, 0);
  font-size: 18px;
}

button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: rgb(55, 99, 174);
  background-color: #0000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
  max-width: 900px;
}

a {
  text-decoration: none;
  font-size: 22px;
  color: black;
}

button:hover, a:hover {
  opacity: 0.7;
}
</style>
<html>
<body background="{% static 'homeBackground.svg' %}">
<div class="card">
  <!-- <img src="img.jpg" alt="John" style="width:100%"> -->
  <h1>{{ user.name }}</h1>
  <h2> Total marked 1 </h2>
  <a href="#"><i class="fa fa-graduation-cap"></i></a>
  <a href="#"><i class="fa fa-fire"></i></a>
  <a href="#"><i class="fa fa-heartf"></i></a>
  <br>
  <br>
  <br>
  <br>
      {% for comment in user.comment_set.all %}
         
  <button>

   {% if comment.agreement %} <i class="fa fa-plus"></i>{% else %}<i class="fa fa-minus"></i> {% endif %} {{comment.opinion}}| {{comment.line.article.link}}
    </button>
    <br>{% endfor %}
    <button><p>Back to home</p></button>
    <!-- <button><p><i class="fa fa-backspace"></i></p></button> -->
</div>

</body>
</html>